# =============================================
# Configuraci�n de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuarios
db.username=root
db.password=

# =============================================
# Configuraci�n SMTP (JavaMail)
# =============================================
smtp.host=sandbox.smtp.mailtrap.io
smtp.port=2525
smtp.username=c4de4a0cfdf8f2
smtp.password=d42d60515aec9e
smtp.from.address=admin@sistema.com
smtp.from.name=Gesti�n de Usuarios

